---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tbtouris/api/

    # Deploy the build folder
    - /bin/cp -R build $DEPLOYPATH

    # Create the frontend directory if it doesn't exist
    - mkdir -p $DEPLOYPATH/frontend

    # Deploy the dist folder into the frontend folder
    - /bin/cp -R frontend/dist $DEPLOYPATH/frontend/
