name: 🚀 Deploy website on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      - name: 🔨 Build Project Locally
        run: |
          npm install
          npm run build
      - name: 📂 Sync files to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ vars.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /home/tbtouris/api/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/frontend/node_modules/**
            **/backend/node_modules/**
      - name: 🔧 Install and Build on Server
        run: >
          sshpass -p "${{ vars.SSH_PASSWORD }}" ssh -o
          StrictHostKeyChecking=no -T -p ${{ vars.SSH_PORT }} ${{
          vars.SSH_USER }}@${{ vars.SSH_HOST }} << 'EOF'
            cd /home/tbtouris/api
            npm install
            npm run build
          EOF
        env:
          SSH_PASSWORD: ${{ vars.SSH_PASSWORD }}
          SSH_USER: ${{ vars.SSH_USER }}
          SSH_HOST: ${{ vars.SSH_HOST }}
          SSH_PORT: ${{ vars.SSH_PORT }}
